export default {
    AF: { name: "Afghanistan", dialCode: "+93", countryCode: "AF" },
    AL: { name: "Albania", dialCode: "+355", countryCode: "AL" },
    DZ: { name: "Algeria", dialCode: "+213", countryCode: "DZ" },
    AS: { name: "American Samoa", dialCode: "+1-684", countryCode: "AS" },
    AD: { name: "Andorra", dialCode: "+376", countryCode: "AD" },
    AO: { name: "Angola", dialCode: "+244", countryCode: "AO" },
    AI: { name: "Anguilla", dialCode: "+1-264", countryCode: "AI" },
    AQ: { name: "Antarctica", dialCode: "+672", countryCode: "AQ" },
    AG: { name: "Antigua and Barbuda", dialCode: "+1-268", countryCode: "AG" },
    AR: { name: "Argentina", dialCode: "+54", countryCode: "AR" },
    AM: { name: "Armenia", dialCode: "+374", countryCode: "AM" },
    AW: { name: "Aruba", dialCode: "+297", countryCode: "AW" },
    AU: { name: "Australia", dialCode: "+61", countryCode: "AU" },
    AT: { name: "Austria", dialCode: "+43", countryCode: "AT" },
    AZ: { name: "Azerbaijan", dialCode: "+994", countryCode: "AZ" },
    BS: { name: "Bahamas", dialCode: "+1-242", countryCode: "BS" },
    BH: { name: "Bahrain", dialCode: "+973", countryCode: "BH" },
    BD: { name: "Bangladesh", dialCode: "+880", countryCode: "BD" },
    BB: { name: "Barbados", dialCode: "+1-246", countryCode: "BB" },
    BY: { name: "Belarus", dialCode: "+375", countryCode: "BY" },
    BE: { name: "Belgium", dialCode: "+32", countryCode: "BE" },
    BZ: { name: "Belize", dialCode: "+501", countryCode: "BZ" },
    BJ: { name: "Benin", dialCode: "+229", countryCode: "BJ" },
    BM: { name: "Bermuda", dialCode: "+1-441", countryCode: "BM" },
    BT: { name: "Bhutan", dialCode: "+975", countryCode: "BT" },
    BO: { name: "Bolivia", dialCode: "+591", countryCode: "BO" },
    BA: { name: "Bosnia and Herzegovina", dialCode: "+387", countryCode: "BA" },
    BW: { name: "Botswana", dialCode: "+267", countryCode: "BW" },
    BR: { name: "Brazil", dialCode: "+55", countryCode: "BR" },
    IO: {
        name: "British Indian Ocean Territory",
        dialCode: "+246",
        countryCode: "IO",
    },
    VG: {
        name: "British Virgin Islands",
        dialCode: "+1-284",
        countryCode: "VG",
    },
    BN: { name: "Brunei", dialCode: "+673", countryCode: "BN" },
    BG: { name: "Bulgaria", dialCode: "+359", countryCode: "BG" },
    BF: { name: "Burkina Faso", dialCode: "+226", countryCode: "BF" },
    BI: { name: "Burundi", dialCode: "+257", countryCode: "BI" },
    KH: { name: "Cambodia", dialCode: "+855", countryCode: "KH" },
    CM: { name: "Cameroon", dialCode: "+237", countryCode: "CM" },
    CA: { name: "Canada", dialCode: "+1", countryCode: "CA" },
    CV: { name: "Cape Verde", dialCode: "+238", countryCode: "CV" },
    KY: { name: "Cayman Islands", dialCode: "+1-345", countryCode: "KY" },
    CF: {
        name: "Central African Republic",
        dialCode: "+236",
        countryCode: "CF",
    },
    TD: { name: "Chad", dialCode: "+235", countryCode: "TD" },
    CL: { name: "Chile", dialCode: "+56", countryCode: "CL" },
    CN: { name: "China", dialCode: "+86", countryCode: "CN" },
    CX: { name: "Christmas Island", dialCode: "+61", countryCode: "CX" },
    CC: { name: "Cocos Islands", dialCode: "+61", countryCode: "CC" },
    CO: { name: "Colombia", dialCode: "+57", countryCode: "CO" },
    KM: { name: "Comoros", dialCode: "+269", countryCode: "KM" },
    CK: { name: "Cook Islands", dialCode: "+682", countryCode: "CK" },
    CR: { name: "Costa Rica", dialCode: "+506", countryCode: "CR" },
    HR: { name: "Croatia", dialCode: "+385", countryCode: "HR" },
    CU: { name: "Cuba", dialCode: "+53", countryCode: "CU" },
    CW: { name: "Curacao", dialCode: "+599", countryCode: "CW" },
    CY: { name: "Cyprus", dialCode: "+357", countryCode: "CY" },
    CZ: { name: "Czech Republic", dialCode: "+420", countryCode: "CZ" },
    CD: {
        name: "Democratic Republic of the Congo",
        dialCode: "+243",
        countryCode: "CD",
    },
    DK: { name: "Denmark", dialCode: "+45", countryCode: "DK" },
    DJ: { name: "Djibouti", dialCode: "+253", countryCode: "DJ" },
    DM: { name: "Dominica", dialCode: "+1-767", countryCode: "DM" },
    DO: {
        name: "Dominican Republic",
        dialCode: "+1-809, 1-829, 1-849",
        countryCode: "DO",
    },
    TL: { name: "East Timor", dialCode: "+670", countryCode: "TL" },
    EC: { name: "Ecuador", dialCode: "+593", countryCode: "EC" },
    EG: { name: "Egypt", dialCode: "+20", countryCode: "EG" },
    SV: { name: "El Salvador", dialCode: "+503", countryCode: "SV" },
    GQ: { name: "Equatorial Guinea", dialCode: "+240", countryCode: "GQ" },
    ER: { name: "Eritrea", dialCode: "+291", countryCode: "ER" },
    EE: { name: "Estonia", dialCode: "+372", countryCode: "EE" },
    ET: { name: "Ethiopia", dialCode: "+251", countryCode: "ET" },
    FK: { name: "Falkland Islands", dialCode: "+500", countryCode: "FK" },
    FO: { name: "Faroe Islands", dialCode: "+298", countryCode: "FO" },
    FJ: { name: "Fiji", dialCode: "+679", countryCode: "FJ" },
    FI: { name: "Finland", dialCode: "+358", countryCode: "FI" },
    FR: { name: "France", dialCode: "+33", countryCode: "FR" },
    PF: { name: "French Polynesia", dialCode: "+689", countryCode: "PF" },
    GA: { name: "Gabon", dialCode: "+241", countryCode: "GA" },
    GM: { name: "Gambia", dialCode: "+220", countryCode: "GM" },
    GE: { name: "Georgia", dialCode: "+995", countryCode: "GE" },
    DE: { name: "Germany", dialCode: "+49", countryCode: "DE" },
    GH: { name: "Ghana", dialCode: "+233", countryCode: "GH" },
    GI: { name: "Gibraltar", dialCode: "+350", countryCode: "GI" },
    GR: { name: "Greece", dialCode: "+30", countryCode: "GR" },
    GL: { name: "Greenland", dialCode: "+299", countryCode: "GL" },
    GD: { name: "Grenada", dialCode: "+1-473", countryCode: "GD" },
    GU: { name: "Guam", dialCode: "+1-671", countryCode: "GU" },
    GT: { name: "Guatemala", dialCode: "+502", countryCode: "GT" },
    GG: { name: "Guernsey", dialCode: "+44-1481", countryCode: "GG" },
    GN: { name: "Guinea", dialCode: "+224", countryCode: "GN" },
    GW: { name: "Guinea-Bissau", dialCode: "+245", countryCode: "GW" },
    GY: { name: "Guyana", dialCode: "+592", countryCode: "GY" },
    HT: { name: "Haiti", dialCode: "+509", countryCode: "HT" },
    HN: { name: "Honduras", dialCode: "+504", countryCode: "HN" },
    HK: { name: "Hong Kong", dialCode: "+852", countryCode: "HK" },
    HU: { name: "Hungary", dialCode: "+36", countryCode: "HU" },
    IS: { name: "Iceland", dialCode: "+354", countryCode: "IS" },
    IN: { name: "India", dialCode: "+91", countryCode: "IN" },
    ID: { name: "Indonesia", dialCode: "+62", countryCode: "ID" },
    IR: { name: "Iran", dialCode: "+98", countryCode: "IR" },
    IQ: { name: "Iraq", dialCode: "+964", countryCode: "IQ" },
    IE: { name: "Ireland", dialCode: "+353", countryCode: "IE" },
    IM: { name: "Isle of Man", dialCode: "+44-1624", countryCode: "IM" },
    IL: { name: "Israel", dialCode: "+972", countryCode: "IL" },
    IT: { name: "Italy", dialCode: "+39", countryCode: "IT" },
    CI: { name: "Ivory Coast", dialCode: "+225", countryCode: "CI" },
    JM: { name: "Jamaica", dialCode: "+1-876", countryCode: "JM" },
    JP: { name: "Japan", dialCode: "+81", countryCode: "JP" },
    JE: { name: "Jersey", dialCode: "+44-1534", countryCode: "JE" },
    JO: { name: "Jordan", dialCode: "+962", countryCode: "JO" },
    KZ: { name: "Kazakhstan", dialCode: "+7", countryCode: "KZ" },
    KE: { name: "Kenya", dialCode: "+254", countryCode: "KE" },
    KI: { name: "Kiribati", dialCode: "+686", countryCode: "KI" },
    XK: { name: "Kosovo", dialCode: "+383", countryCode: "XK" },
    KW: { name: "Kuwait", dialCode: "+965", countryCode: "KW" },
    KG: { name: "Kyrgyzstan", dialCode: "+996", countryCode: "KG" },
    LA: { name: "Laos", dialCode: "+856", countryCode: "LA" },
    LV: { name: "Latvia", dialCode: "+371", countryCode: "LV" },
    LB: { name: "Lebanon", dialCode: "+961", countryCode: "LB" },
    LS: { name: "Lesotho", dialCode: "+266", countryCode: "LS" },
    LR: { name: "Liberia", dialCode: "+231", countryCode: "LR" },
    LY: { name: "Libya", dialCode: "+218", countryCode: "LY" },
    LI: { name: "Liechtenstein", dialCode: "+423", countryCode: "LI" },
    LT: { name: "Lithuania", dialCode: "+370", countryCode: "LT" },
    LU: { name: "Luxembourg", dialCode: "+352", countryCode: "LU" },
    MO: { name: "Macau", dialCode: "+853", countryCode: "MO" },
    MK: { name: "Macedonia", dialCode: "+389", countryCode: "MK" },
    MG: { name: "Madagascar", dialCode: "+261", countryCode: "MG" },
    MW: { name: "Malawi", dialCode: "+265", countryCode: "MW" },
    MY: { name: "Malaysia", dialCode: "+60", countryCode: "MY" },
    MV: { name: "Maldives", dialCode: "+960", countryCode: "MV" },
    ML: { name: "Mali", dialCode: "+223", countryCode: "ML" },
    MT: { name: "Malta", dialCode: "+356", countryCode: "MT" },
    MH: { name: "Marshall Islands", dialCode: "+692", countryCode: "MH" },
    MR: { name: "Mauritania", dialCode: "+222", countryCode: "MR" },
    MU: { name: "Mauritius", dialCode: "+230", countryCode: "MU" },
    YT: { name: "Mayotte", dialCode: "+262", countryCode: "YT" },
    MX: { name: "Mexico", dialCode: "+52", countryCode: "MX" },
    FM: { name: "Micronesia", dialCode: "+691", countryCode: "FM" },
    MD: { name: "Moldova", dialCode: "+373", countryCode: "MD" },
    MC: { name: "Monaco", dialCode: "+377", countryCode: "MC" },
    MN: { name: "Mongolia", dialCode: "+976", countryCode: "MN" },
    ME: { name: "Montenegro", dialCode: "+382", countryCode: "ME" },
    MS: { name: "Montserrat", dialCode: "+1-664", countryCode: "MS" },
    MA: { name: "Morocco", dialCode: "+212", countryCode: "MA" },
    MZ: { name: "Mozambique", dialCode: "+258", countryCode: "MZ" },
    MM: { name: "Myanmar", dialCode: "+95", countryCode: "MM" },
    NA: { name: "Namibia", dialCode: "+264", countryCode: "NA" },
    NR: { name: "Nauru", dialCode: "+674", countryCode: "NR" },
    NP: { name: "Nepal", dialCode: "+977", countryCode: "NP" },
    NL: { name: "Netherlands", dialCode: "+31", countryCode: "NL" },
    AN: { name: "Netherlands Antilles", dialCode: "+599", countryCode: "AN" },
    NC: { name: "New Caledonia", dialCode: "+687", countryCode: "NC" },
    NZ: { name: "New Zealand", dialCode: "+64", countryCode: "NZ" },
    NI: { name: "Nicaragua", dialCode: "+505", countryCode: "NI" },
    NE: { name: "Niger", dialCode: "+227", countryCode: "NE" },
    NG: { name: "Nigeria", dialCode: "+234", countryCode: "NG" },
    NU: { name: "Niue", dialCode: "+683", countryCode: "NU" },
    KP: { name: "North Korea", dialCode: "+850", countryCode: "KP" },
    MP: {
        name: "Northern Mariana Islands",
        dialCode: "+1-670",
        countryCode: "MP",
    },
    NO: { name: "Norway", dialCode: "+47", countryCode: "NO" },
    OM: { name: "Oman", dialCode: "+968", countryCode: "OM" },
    PK: { name: "Pakistan", dialCode: "+92", countryCode: "PK" },
    PW: { name: "Palau", dialCode: "+680", countryCode: "PW" },
    PS: { name: "Palestine", dialCode: "+970", countryCode: "PS" },
    PA: { name: "Panama", dialCode: "+507", countryCode: "PA" },
    PG: { name: "Papua New Guinea", dialCode: "+675", countryCode: "PG" },
    PY: { name: "Paraguay", dialCode: "+595", countryCode: "PY" },
    PE: { name: "Peru", dialCode: "+51", countryCode: "PE" },
    PH: { name: "Philippines", dialCode: "+63", countryCode: "PH" },
    PN: { name: "Pitcairn", dialCode: "+64", countryCode: "PN" },
    PL: { name: "Poland", dialCode: "+48", countryCode: "PL" },
    PT: { name: "Portugal", dialCode: "+351", countryCode: "PT" },
    PR: { name: "Puerto Rico", dialCode: "+1-787, 1-939", countryCode: "PR" },
    QA: { name: "Qatar", dialCode: "+974", countryCode: "QA" },
    CG: { name: "Republic of the Congo", dialCode: "+242", countryCode: "CG" },
    RE: { name: "Reunion", dialCode: "+262", countryCode: "RE" },
    RO: { name: "Romania", dialCode: "+40", countryCode: "RO" },
    RU: { name: "Russia", dialCode: "+7", countryCode: "RU" },
    RW: { name: "Rwanda", dialCode: "+250", countryCode: "RW" },
    BL: { name: "Saint Barthelemy", dialCode: "+590", countryCode: "BL" },
    SH: { name: "Saint Helena", dialCode: "+290", countryCode: "SH" },
    KN: {
        name: "Saint Kitts and Nevis",
        dialCode: "+1-869",
        countryCode: "KN",
    },
    LC: { name: "Saint Lucia", dialCode: "+1-758", countryCode: "LC" },
    MF: { name: "Saint Martin", dialCode: "+590", countryCode: "MF" },
    PM: {
        name: "Saint Pierre and Miquelon",
        dialCode: "+508",
        countryCode: "PM",
    },
    VC: {
        name: "Saint Vincent and the Grenadines",
        dialCode: "+1-784",
        countryCode: "VC",
    },
    WS: { name: "Samoa", dialCode: "+685", countryCode: "WS" },
    SM: { name: "San Marino", dialCode: "+378", countryCode: "SM" },
    ST: { name: "Sao Tome and Principe", dialCode: "+239", countryCode: "ST" },
    SA: { name: "Saudi Arabia", dialCode: "+966", countryCode: "SA" },
    SN: { name: "Senegal", dialCode: "+221", countryCode: "SN" },
    RS: { name: "Serbia", dialCode: "+381", countryCode: "RS" },
    SC: { name: "Seychelles", dialCode: "+248", countryCode: "SC" },
    SL: { name: "Sierra Leone", dialCode: "+232", countryCode: "SL" },
    SG: { name: "Singapore", dialCode: "+65", countryCode: "SG" },
    SX: { name: "Sint Maarten", dialCode: "+1-721", countryCode: "SX" },
    SK: { name: "Slovakia", dialCode: "+421", countryCode: "SK" },
    SI: { name: "Slovenia", dialCode: "+386", countryCode: "SI" },
    SB: { name: "Solomon Islands", dialCode: "+677", countryCode: "SB" },
    SO: { name: "Somalia", dialCode: "+252", countryCode: "SO" },
    ZA: { name: "South Africa", dialCode: "+27", countryCode: "ZA" },
    KR: { name: "South Korea", dialCode: "+82", countryCode: "KR" },
    SS: { name: "South Sudan", dialCode: "+211", countryCode: "SS" },
    ES: { name: "Spain", dialCode: "+34", countryCode: "ES" },
    LK: { name: "Sri Lanka", dialCode: "+94", countryCode: "LK" },
    SD: { name: "Sudan", dialCode: "+249", countryCode: "SD" },
    SR: { name: "Suriname", dialCode: "+597", countryCode: "SR" },
    SJ: { name: "Svalbard and Jan Mayen", dialCode: "+47", countryCode: "SJ" },
    SZ: { name: "Swaziland", dialCode: "+268", countryCode: "SZ" },
    SE: { name: "Sweden", dialCode: "+46", countryCode: "SE" },
    CH: { name: "Switzerland", dialCode: "+41", countryCode: "CH" },
    SY: { name: "Syria", dialCode: "+963", countryCode: "SY" },
    TW: { name: "Taiwan", dialCode: "+886", countryCode: "TW" },
    TJ: { name: "Tajikistan", dialCode: "+992", countryCode: "TJ" },
    TZ: { name: "Tanzania", dialCode: "+255", countryCode: "TZ" },
    TH: { name: "Thailand", dialCode: "+66", countryCode: "TH" },
    TG: { name: "Togo", dialCode: "+228", countryCode: "TG" },
    TK: { name: "Tokelau", dialCode: "+690", countryCode: "TK" },
    TO: { name: "Tonga", dialCode: "+676", countryCode: "TO" },
    TT: { name: "Trinidad and Tobago", dialCode: "+1-868", countryCode: "TT" },
    TN: { name: "Tunisia", dialCode: "+216", countryCode: "TN" },
    TR: { name: "Turkey", dialCode: "+90", countryCode: "TR" },
    TM: { name: "Turkmenistan", dialCode: "+993", countryCode: "TM" },
    TC: {
        name: "Turks and Caicos Islands",
        dialCode: "+1-649",
        countryCode: "TC",
    },
    TV: { name: "Tuvalu", dialCode: "+688", countryCode: "TV" },
    VI: { name: "U.S. Virgin Islands", dialCode: "+1-340", countryCode: "VI" },
    UG: { name: "Uganda", dialCode: "+256", countryCode: "UG" },
    UA: { name: "Ukraine", dialCode: "+380", countryCode: "UA" },
    AE: { name: "United Arab Emirates", dialCode: "+971", countryCode: "AE" },
    GB: { name: "United Kingdom", dialCode: "+44", countryCode: "GB" },
    US: { name: "United States", dialCode: "+1", countryCode: "US" },
    UY: { name: "Uruguay", dialCode: "+598", countryCode: "UY" },
    UZ: { name: "Uzbekistan", dialCode: "+998", countryCode: "UZ" },
    VU: { name: "Vanuatu", dialCode: "+678", countryCode: "VU" },
    VA: { name: "Vatican", dialCode: "+379", countryCode: "VA" },
    VE: { name: "Venezuela", dialCode: "+58", countryCode: "VE" },
    VN: { name: "Vietnam", dialCode: "+84", countryCode: "VN" },
    WF: { name: "Wallis and Futuna", dialCode: "+681", countryCode: "WF" },
    EH: { name: "Western Sahara", dialCode: "+212", countryCode: "EH" },
    YE: { name: "Yemen", dialCode: "+967", countryCode: "YE" },
    ZM: { name: "Zambia", dialCode: "+260", countryCode: "ZM" },
    ZW: { name: "Zimbabwe", dialCode: "+263", countryCode: "ZW" },
};
